- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
  vars:
    homebrew_repositories:
    homebrew_packages:
      - brew-cask
      - elasticsearch
      - git
      - hub
      - tig
      - imagemagick
      - jq
      - openssl
      - peco
      - rbenv
      - readline
      - ruby-build
      - the_silver_searcher
      - tmux
      - tree
      - watch
      - wget
      - qt
      - ansible
      - ghostscript
      - mysql56
      - redis
      - memcached
      - nkf
      - scala
      - gradle
      - mongodb
      - heroku-toolbelt
      - composer
      - activemq
      - rabbitmq
      - mycli
      - node
      - packer
      - go
      - nvm
      - highlight
      - speedtest_cli
    homebrew_cask_repositories:
    homebrew_cask_packages:
